name: Continuous Integration
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  shell-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          shellcheck -x -s bash .bashrc .bash_aliases .bash_colors .bash_completions
  
  markdown-lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: lint
        run: |
          npm install -g markdownlint-cli
          markdownlint *.md
